name: Integration

on: push

jobs:
  integration:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['14.x', '16.x', '18.12.1']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        pnpm: [8.5.1]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}

      - name: Setup Node.js (${{ matrix.node }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: pnpm run build
