name: Release

# on:
#   push:
#     branches:
#       - master
#   workflow_dispatch:
#     inputs:

on: push

jobs:
  release:
    name: Release

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['18.12.1']
        os: [ubuntu-latest]
        pnpm: [8.5.1]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}

      - name: Setup Node.js (${{ matrix.node }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: pnpm run semantic-release
