name: Release
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
    inputs:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 14.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      - name: Install deps and build
        run: yarn install --frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
