name: Size

on: [pull_request]

jobs:
  size:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['18.12.1']
        os: [ubuntu-latest]
        pnpm: [8.5.1]

    env:
      CI_JOB_NUMBER: 1

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}

      - name: Setup Node.js (${{ matrix.node }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
